### ISSUE TITLE
which data set needs meta data?

### ISSUE THREAD

**Issue by rBatt** [mpinsky/OceanAdapt#15]
I could do 1 meta data file for the compiled data set, or a meta data file for each of the raw data sets, or (as moderate option), I could do a meta data file for each region, after I do the basic read-in and clean-up of the data set.

Ultimately I guess the meta data needs to match whatever goes on the website. Do we anticipate needing to do anything different for the OA website data in the future?

My approach to this somewhat depends on whether I expect to merge my "trawl" workflow and the OA workflow at some point, or if they should be left as divergent.

For right now, the simple thing to do might be to write the meta data for the OA website data sets based on how they're manipulated in your scripts. The only problem is that those scripts are rather challenging to sift through.

@mpinsky thoughts?

**Comment by mpinsky** [comment]
Hmm. Not fully sure that I understand the options you laid out.

I would say a brief metadata file for each of the original trawl datasets
that goes into OA. To capture a couple key details of the methods, the data
format, and who to contact for more information.

That way, it's useful for OA, useful for you, and useful for whoever uses
these datasets in our lab for other projects down the road. And you don't
have to bother with the scripts.

I don't expect to completely merge your 'trawl' workflow with the OA
workflow, except for the fact that they both pull from the same raw
datasets. As we've learned, each project needs to process the data in
somewhat different ways... Seem reasonable?

**Comment by rBatt** [comment]
Sounds good. Your answer takes care of the issue, even if you didn't fully understand what I was getting at. Thanks.
