### ISSUE TITLE
create basic EML for trawl data

### ISSUE THREAD

**Issue by rBatt** [mpinsky/OceanAdapt#17]
Having trouble doing this right now, but it's the first step. https://github.com/ropensci/EML/issues/129

Later will need to add more detailed meta data.

**Comment by rBatt** [comment]
@mpinsky does this work: https://github.com/mpinsky/OceanAdapt/commit/ce6f8bffbbee8f31a8f7d9445357c0ab5ca95727 ?

That's an example for AI, and is minimal.

The next thing to do would be to add in information about obvious protocol changes, links to documents detailing detectability, net sizes, captains, etc

**Comment by mpinsky** [comment]
Ryan, this looks wonderful. I'd have a few small things to add:

1) A note about what a station is (is it unique within a year? or within a
stratum? are same stations used across years, e.g. a fixed design? or is it
a stratified random design?)
2) A note about whether for whether mass and counts have been corrected for
trawled area or changes in methods/gear. If you don't know, I may be able
to help answer this.
3) Links or information somewhere about how to interpret SID, VESSEL ID, or
other similar numbers. I think this is this kind of extra documentations
you were referring to with your note, though.
4) Your definition of HAUL for AI looks incorrect (it currently says
stratum area). I believe it is something like an ID that counts up from 1
on each cruise.

**Comment by rBatt** [comment]
@mpinsky thanks

1-3) I'm not sure how to go about these things in a standardized way. I think I want to come back to this point after I've gone through all of the regions; that way I can see what they have in common, and how to standardize the descriptions. It might be that each column deserves its own methods description, and that the data set as a whole requires a description of the nested/ crossed structure of the values in the columns. I'm definitely not sure of how to do this.

4) Oops, I thought it was a column called "HAUL Areakm2". Was confusing b/c in the raw format there all sorts of leading and trailing whitespace. I'll fix that. Good catch.

**Comment by rBatt** [comment]
@mpinsky OK, I think I've completed this task for AI, EBS, GOA, GMEX, NEUS, WCANN, and WCTRI.

I have not created meta data for the DFO surveys (NEWF, SHELF, SGULF), nor for SA.

All of these entries still need to be checked, and they do not contain much advanced information.

I will create new issues for what I think needs to be checked still, and reference this issue for those.
