### ISSUE TITLE
define strata to be used for NEUS fall

### ISSUE THREAD

**Issue by rBatt** [mpinsky/OceanAdapt#28]
probably have to use something like this: https://github.com/rBatt/trawl/blob/master/Scripts/DataFunctions/makeStrat.R

no tolerance for missing years

**Comment by rBatt** [comment]
@mpinsky Is it OK to just use same strata as what are currently used for Spring?

**Comment by mpinsky** [comment]
Not necessarily, unfortunately. I'd do a quick check for which strata are
consistently surveyed through time.

e.g.,

table(dat$stratum, dat$year)

then pull out the rows that don't have any zeros.

I think that should do the trick.

**Comment by rBatt** [comment]
@mpinsky I have this fixed, i just can't push. I might just reset my local copy, but I don't want to mess with it right now.

**Comment by rBatt** [comment]
@mpinsky I finally fixed everything so that I can now push to this repo again. I've made this fix. You can see the commit referenced above.
