### ISSUE TITLE
What to do for this (vector units)

### ISSUE THREAD

**Issue by mpinsky** [mpinsky/OceanAdapt#29]
We currently have average latitude and average depth (across all species nationally, within certain regions) as our national indicators. We want to add a new one: average distance moved.

Our plan from 5/14/2015:
- Within each region, average the latitude and longitude offsets from each species' starting point (by year)
- Calculate distance offset for the whole assemblage in each survey (e.g., pythagorean theorem) (by year)
- Average the distances across all surveys (by year) to get a time-series of total distance moved

**Comment by rBatt** [comment]
@mpinsky I changed the name and milestone to relate this to the Vector Units milestone

**Comment by rBatt** [comment]
if half the assemblage moves in one direction, and the other half the species move the same distance in the exact opposite direction, the metric should read 0.

Goal is to create a figure where y-axis is assemblage displacement in km (displacement is averaged across species; need to decide if to average at lat lon stage, or at distance metric (distance and angle)).

**Comment by mpinsky** [comment]
We will drop this for now.
