### ISSUE TITLE
drop all old in update.data.R

### ISSUE THREAD

**Issue by rBatt** [mpinsky/OceanAdapt#31]
https://github.com/mpinsky/OceanAdapt/blob/master/R/update.data.R#L14

Instead of unique, just `updatedAI <- updatedAI0[1:nrow(oldAI)]`. In this case, the `rbind()` still serves as a formatting check; although it's clearly wasteful and not the most elegant way to ensure names and formats match, so should eventually be changed, too.

@mpinsky We just talked about this, so I turned it into an issue.

**Comment by rBatt** [comment]
@mpinsky Now I remember why I did it this way.

http://www.afsc.noaa.gov/RACE/groundfish/survey_data/data.htm

Do you really want to be going back and downloaded each one of those? I had been doing it that way because the newest .csv's don't contain the entire record.

**Comment by mpinsky** [comment]
I see two choices: download them all, or write to the data manager and
verify that the old ones didn't change.

On Monday, August 3, 2015, Ryan Batt <notifications@github.com> wrote:

> @mpinsky <https://github.com/mpinsky> Now I remember why I did it this
> way.
>
> http://www.afsc.noaa.gov/RACE/groundfish/survey_data/data.htm
>
> Do you really want to be going back and downloaded each one of those? I
> had been doing it that way because the newest .csv's don't contain the
> entire record.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mpinsky/OceanAdapt/issues/31#issuecomment-127403310>.
>


-- 
Please excuse, sent from a device with tiny keys...

**Comment by rBatt** [comment]
OK, sounds good.

If the data manager says "I don't know" or "some of them" or "files A, b, c, ...zz34, z^345 files changed", then we'll have to go download them all anyway.

For the Alaskan data sets, the page looks like it should be very susceptible to automatically downloading everything. These are the data sets that have all the files separate.

I'll think on this for now. I won't be changing my current approach too much at the moment, but I realize now that it could cause problems. What I'm working on right now is a sound and documented approach to adding on the most recent piece of data.

**Comment by mpinsky** [comment]
As we discussed today, the approach I would like to take is to download all the data files from each survey, each time we do an update. I do not want us trying to piece old data together with new data.

**Comment by rBatt** [comment]
yep, that's right. working on it right now
