### ISSUE TITLE
OceanAdapt download fails on All regions

### ISSUE THREAD

**Issue by mpinsky** [mpinsky/OceanAdapt#32]
I tried to download the OceanAdapt RAW data for All regions (should be a large file). The circle spins for a while, and then goes silent, with no file available to download. This happened on a Mac in Firefox and Chrome. On the other hand, the download appeared to work fine on a Mac with Safari, where the file downloaded automatically, but the downloaded file was zero bytes. 

Is there something that is timing out?

I was able to download a single region fine.

**Comment by rBatt** [comment]
It's on amphiprion. Are you talking about the website?

**Comment by mpinsky** [comment]
Yes, I am specifically talking about the website.

**Comment by ljmarxen** [comment]
Problem seems to be related to the NEUS dataset.  For some reason the 
database table has an excessive number of records.  We are looking into 
to it to figure out what happened.


On 08/25/2015 09:02 PM, mpinsky wrote:
>
> Yes, I am specifically talking about the website.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mpinsky/OceanAdapt/issues/32#issuecomment-134781878>.
>

-- 
   Lucas Marxen
   Assistant Director of Research Technology
   Office of Research Analytics
   New Jersey Agricultural Experiment Station
   Rutgers, The State University of New Jersey
   Martin Hall, Room 113
   88 Lipman Drive
   New Brunswick, NJ 08901-8525
   Tel: 848-932-4543
   Email: marxen@aesop.rutgers.edu

**Comment by mpinsky** [comment]
Should we re-upload the new NEUS dataset and overwrite?

On Wednesday, August 26, 2015, ljmarxen <notifications@github.com> wrote:

> Problem seems to be related to the NEUS dataset. For some reason the
> database table has an excessive number of records. We are looking into
> to it to figure out what happened.
>
>
> On 08/25/2015 09:02 PM, mpinsky wrote:
> >
> > Yes, I am specifically talking about the website.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mpinsky/OceanAdapt/issues/32#issuecomment-134781878
> >.
> >
>
> --
> Lucas Marxen
> Assistant Director of Research Technology
> Office of Research Analytics
> New Jersey Agricultural Experiment Station
> Rutgers, The State University of New Jersey
> Martin Hall, Room 113
> 88 Lipman Drive
> New Brunswick, NJ 08901-8525
> Tel: 848-932-4543
> Email: marxen@aesop.rutgers.edu
> <javascript:_e(%7B%7D,'cvml','marxen@aesop.rutgers.edu');>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mpinsky/OceanAdapt/issues/32#issuecomment-134991623>.
>


-- 
Please excuse, sent from a device with tiny keys...

**Comment by ljmarxen** [comment]
No. Dan took care of it.  Seems to be a problem with the script on our 
end with the data upload.  NEUS does not have any form of unique 
identifier to distinguish between records, so we had code that was 
comparing certain field values to check for duplicates when inserting 
records.  It doesn't seem to be working properly because there were 
about four times as many records in the table then there should have 
been.  Dan had the system do a record comparison using every field and 
was able to remove the duplicates.  The download feature should be 
working now

On 08/26/2015 08:46 AM, mpinsky wrote:
> Should we re-upload the new NEUS dataset and overwrite?
>
> On Wednesday, August 26, 2015, ljmarxen <notifications@github.com> wrote:
>
> > Problem seems to be related to the NEUS dataset. For some reason the
> > database table has an excessive number of records. We are looking into
> > to it to figure out what happened.
> >
> >
> > On 08/25/2015 09:02 PM, mpinsky wrote:
> > >
> > > Yes, I am specifically talking about the website.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/mpinsky/OceanAdapt/issues/32#issuecomment-134781878
> > >.
> > >
> >
> > --
> > Lucas Marxen
> > Assistant Director of Research Technology
> > Office of Research Analytics
> > New Jersey Agricultural Experiment Station
> > Rutgers, The State University of New Jersey
> > Martin Hall, Room 113
> > 88 Lipman Drive
> > New Brunswick, NJ 08901-8525
> > Tel: 848-932-4543
> > Email: marxen@aesop.rutgers.edu
> > <javascript:_e(%7B%7D,'cvml','marxen@aesop.rutgers.edu');>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/mpinsky/OceanAdapt/issues/32#issuecomment-134991623>.
> >
>
>
> -- 
> Please excuse, sent from a device with tiny keys...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mpinsky/OceanAdapt/issues/32#issuecomment-134992995>.
>

-- 
   Lucas Marxen
   Assistant Director of Research Technology
   Office of Research Analytics
   New Jersey Agricultural Experiment Station
   Rutgers, The State University of New Jersey
   Martin Hall, Room 113
   88 Lipman Drive
   New Brunswick, NJ 08901-8525
   Tel: 848-932-4543
   Email: marxen@aesop.rutgers.edu

**Comment by mpinsky** [comment]
Just tested, and it now works. Perfect!
