### ISSUE TITLE
goa doesn't work

### ISSUE THREAD

**Issue by rBatt** [mpinsky/OceanAdapt#36]
ran into issue trying to update goa region

@mpinsky i guess this means that the different years had different number of columns

<img width="1439" alt="screen shot 2015-08-27 at 3 10 04 am" src="https://cloud.githubusercontent.com/assets/5630847/9514583/3c0325ae-4c69-11e5-8d67-4cc118228cc2.png">

**EDIT:** This is on the `updates` branch

**Comment by rBatt** [comment]
@mpinsky I have a crappy fix for this for the moment, just for the purposes of trying to get the code almost working like it was before: I took a suggestion from the error message, and set `fill=TRUE` (data.table method for `rbind` I guess). I just need to get the files there so that I can figure out how to get the flow working like it was before.

**Comment by mpinsky** [comment]
I just read in the four new goa files (from goa/2015-08-26.zip) and they
rbinded together with no errors. All the column names are exactly the same
as well. I'm confused why you got an error!

**Comment by rBatt** [comment]
@mpinsky working on testing and fixing all of this

**Comment by rBatt** [comment]
@mpinsky I think some of the problems were due to `404: Sleep file not found; put head on pillow to refresh page`

**Comment by rBatt** [comment]
@mpinsky also, were you on the `updates` branch, or `master`? I'm working on `updates`.

I think I've almost fixed other problems (not the problem this discussion is about, sorry off-topic)
