### ISSUE TITLE
Website common names need to be updated

### ISSUE THREAD

**Issue by mpinsky** [mpinsky/OceanAdapt#4]
Malin has a new file, spptaxonomy_2015-04-09_plusManual.csv, with a spiny dogfish and yellowtail flounder names corrected (were incorrect before). These need to be sent to Lucas Marxen and incorporated.

**Comment by rBatt** [comment]
@mpinsky It'll be good to get information back from Rachel after her manual grooming of the entire set of species names. 

Ultimately it would be good to cease working from manually generated csv files, and do something with a better-documented history.

**Comment by mpinsky** [comment]
This has now been fixed.
