### ISSUE TITLE
Adding zeros

### ISSUE THREAD

**Issue by mpinsky** [mpinsky/OceanAdapt#43]
@rBatt @ljmarxen 

I believe the latest commit 2c3320438d4622a44795c7af73d11732a6901299 will now properly add zeros to our set of species (see table created [here](https://github.com/mpinsky/OceanAdapt/blob/2c3320438d4622a44795c7af73d11732a6901299/complete_r_script.R#L1279)). This will allow Lucas to make maps.

Ryan, you may want to take a look at my [edit](https://github.com/mpinsky/OceanAdapt/blob/2c3320438d4622a44795c7af73d11732a6901299/complete_r_script.R#L868) to explode0() to get it to add zeros instead of NAs It may not be the best way to do it with data.tables.

**Comment by rBatt** [comment]
Oops.

another way:

out[is.na(wtcpue), wtcpue:=0]

No need to reassign. Slightly faster because it doesn't have to copy the
entire object.

Thanks though. I lost track of the objective when focusing on he merge.
