### ISSUE TITLE
Typo in correcting roughtail stingray?

### ISSUE THREAD

**Issue by rBatt** [mpinsky/OceanAdapt#45]
https://github.com/mpinsky/OceanAdapt/blob/master/complete_r_script.R#L247

@JWMorley 

When doing this for my version of the trawl data set if I do `X[SPECIESCODE==8713050104]` I get output (340 lines). 

When I do `X[haulid==20010106] # my haulid is the original COLLECTIONNUMBER` I get 26 lines of output.

But if I do `X[haulid==20010106 & SPECIESCODE==8713050104]`, I don't get anything.

Is this a typo of sorts?

**Comment by rBatt** [comment]
Note that this relates to rBatt/trawlData#6

**Comment by JWMorley** [comment]
'haulid' is made from EVENTNAME, not COLLECTIONNUMBER, which I think you
know. The first and last line of code makes sense, but I'm not sure why
`X[haulid==20010106] would produce anything, because there is no EVENTNAME
with that number.....

**Comment by rBatt** [comment]
Actually, I didn't know. I must have messed that up. Crap. 

I probably never noticed because I was only using the inner strata (are the 2 collections per event reflecting 1 inner and 1 outer per event??).

I'll be in today and ask in person. Thanks for helping me sort this out.

**Comment by rBatt** [comment]
Given that I may have used the wrong column for `haulid`, this still doesn't explain why I don't get any output for that last line.

**Comment by JWMorley** [comment]
The two COLLECTIONNUMBERS are basically replicate tows within an
EVENTNAME. The catches of each COLLECTIONNUMBER are conducted
independently, but all other variables (depth, strata, temperature, gps,
etc.) are identical within an EVENTNAME.

You most likely will want to drop the outer strata of seus entirely. They
were only sampled for 10 years in spring and fall, and were of limited
latitude coverage.

**Comment by rBatt** [comment]
OK, gotcha. I did drop the Outer strata for those reasons.

Is this a situation where there's a net hanging off of each side of the boat, or are the towing through the area two separate times?

**Comment by JWMorley** [comment]
They're towed at the same time, and I think the two nets are connected to
eachother (ie share a center trawl-door or something like that).
