### ISSUE TITLE
SEUS files in data vis have \CR at end of header line?!

### ISSUE THREAD

**Issue by rBatt** [mpinsky/OceanAdapt#46]
For some reason these files contain at least 2 types of end-of-line indicators.

This is such an annoying issue whenever it pops up.

I don't know the ultimate source of the problem. The other regions don't have the issue.

Can just open the file an delete the <CR> (that's what I see in TextMate).

It's probably just a CRLF at the end of the first line, and LF everywhere else, so TM (and `data.table::fread()`) see the bonus indicator as an extra character, not as a CRLF character. That's my guess.

I think `read.csv()` is clever enough to read it in properly, though.

**Comment by rBatt** [comment]
@mpinsky @danfarns Is this intended? Seems odd.

**Comment by mpinsky** [comment]
I can't think of a reason. Jim knows the dataset better, and perhaps could ask the SEUS data manager if it's an issue. My guess is a strange export from the database they use.

**Comment by mstuart1** [comment]
read_csv appears to deal with this issue.
