### ISSUE TITLE
Trouble uploading GMEX to Ocean Adapt; what's the right format?

### ISSUE THREAD

**Issue by rBatt** [mpinsky/OceanAdapt#47]
@mpinsky @ljmarxen @danfarns 

I'm having trouble uploading a GMEX zip file to the Ocean Adapt website.

[I've tried the one that Malin last used which (I think) worked for him](https://github.com/mpinsky/OceanAdapt/blob/master/data_updates/Data_Updated/gmex_newstsation.zip)

[I've also tried the format I had been using previous to that](https://github.com/mpinsky/OceanAdapt/blob/master/data_updates/Data_Updated/gmex.zip)

[Lastly, I've been trying to upload all the data sets, and my newest GMEX zip file won't work either (this not on master branch yet)](https://github.com/mpinsky/OceanAdapt/blob/update2016/data_updates/Data_Updated/gmex.zip)

I've put fair chunk of time into fiddling around with it, so I'm asking for some help here.

1. If you look at the 3rd zip file I linked above, do you see a problem with any of those files?
2. If unable to find a problem in what I'm uploading, does someone have a working example of a gmex.zip file? I've tried several and can't get them to work.

Just FYI, I did replace `\"` with `""` in the station file.

**Comment by mpinsky** [comment]
We are transitioning to a new system where complete_r_script.r reads directly from the raw files. No longer need to upload, so this issue isn't relevant any more.
