### ISSUE TITLE
Machine readable file for acceptable column names, format

### ISSUE THREAD

**Issue by rBatt** [mpinsky/OceanAdapt#48]
For the past 2 updates for Ocean Adapt, it's proven difficult to upload the new data sets. It is my understanding that the website was originally designed to accept the data files formatted according to their original formats (i.e., the 'raw' format).

The problem here is that the data aren't always received in exactly the same format, and there is no record of what the file formats (contents, too) should be so that they can be accepted by the OA website upload. Even past uploads cannot be relied upon entirely, it seems (see #47).

I put together a document with [human-readable column names for each region](https://github.com/mpinsky/OceanAdapt/blob/master/metaData/oa_upload_colNames.txt), but this is not as useful as it could be for documenting the column names for data updates, because it's not in a format that's easily read into R (which is the environment used to prepare the data for upload).

Furthermore, column names are not the only component of formatting that needs attention. Some formatting corrections (see #42 ) are rather idiosyncratic. These aspects would not need to be documented for all files and regions, and can remain as steps in the [data update readme](https://github.com/mpinsky/OceanAdapt/blob/master/How_to_update.md) and/ or [in the code that updates that data set](https://github.com/mpinsky/OceanAdapt/blob/update2016/R/update.data.R#L302-L342). However, items such as the "class" (in R) for each column might be useful to record, as would the more general quoting preferences (for each region and file, should characters be wrapped in ""?).

Currently, old upload files are being used as references/ guidelines. However, this is not an explicit definition of the OA database's expectation for format, and as proven unreliable as a way to ensure acceptable data formatting.

I propose we create 3 types of reference files for each file / region:
1. the exact column headers  
2. the class (in R) of the content for each column  
3. whether characters should be wrapped in quotes  

@mpinsky Any thoughts here?

@ljmarxen @danfarns Once we get #47 sorted out, and if Malin thinks a standard like this would be useful, would you be able to work with me to make sure that these formatting guidelines indeed reflect what should be uploaded to OA?

**Comment by mpinsky** [comment]
This seems like a great discussion point for our meeting on 7/7, coupled with any other ideas that Lucas and Dan have about how to deal with the constant, small changes in formats.

**Comment by mstuart1** [comment]
It appears this issue was resolved on 7/7/2016
