### ISSUE TITLE
Changes species names to not contain space b/w genus and species

### ISSUE THREAD

**Issue by rBatt** [mpinsky/OceanAdapt#53]
@mpinsky Is this intentional?

https://github.com/mpinsky/OceanAdapt/blob/master/complete_r_script.R#L624-L627

**Comment by rBatt** [comment]
Also, it looks like a lot of the names trying to be matched do not contain spaces, either. I will glance at this history of the file and see if maybe it was accidentally changed at some point, just struck me as peculiar.

**Comment by mpinsky** [comment]
Yes, that was intentional. These were groups of species that had not
historically been identified separately (but are now identified
separately). Lumping them gave us a longer timeseries for the group.

This is one of many decisions that could be revisited. But we don't need to
revisit it now.

**Comment by rBatt** [comment]
I don't think you understand what I'm pointing out. There are strings like "Atheresthesevermanni"

**Comment by mpinsky** [comment]
When that code was written, some of the values in the spp column of ai were
"Atheresthesevermanni" and similar.

**Comment by rBatt** [comment]
Ok. They're also set to stuff like 'Atheresthessp.'

But after digger through the history of the file, I found that these lines have remained unchanged since your initial commit, so I'm less concerned. 

Before I close this, is there a reason to set the name to 'Atheresthessp.' ? I can understand matching what was there previously (e.g., in the case of A. evermanni), but it's harder to imagine why it'd be corrected to Atheresthessp instead of Atheresthes sp

**Comment by mpinsky** [comment]
No specific reason.

However, think carefully before fixing things that aren't broken. I don't
off the top of my head know if anything else depends on that.

**Comment by rBatt** [comment]
Nope, not changing! I only brought this up b.c the peculiarity thought maybe it was a recent change. After that I was just satisfying curiosity. Thanks.

**Comment by rBatt** [comment]
Closing b/c this is intentional, though not it isn't clear whether or not it is needed.
