### ISSUE TITLE
i think seus file in top level can be deleted?

### ISSUE THREAD

**Issue by rBatt** [mpinsky/OceanAdapt#58]
https://github.com/mpinsky/OceanAdapt/blob/master/seus_strata.csv

it's also in the updated zip file, too. the script that creates the data_updated zip file pull in the seus_strata from the data_raw, not that top level file

**Comment by mstuart1** [comment]
I deleted it.

**Comment by mstuart1** [comment]
This is a test for a demonstration.

**Comment by mstuart1** [comment]
Testing over
