### ISSUE TITLE
Known issues with SEUS data extraction

### ISSUE THREAD

**Issue by mpinsky** [mpinsky/OceanAdapt#59]
From: Jeanne Boylan <BoylanJ@dnr.sc.gov>
Date: Fri, Jul 28, 2017 at 2:53 PM
Subject: Notification of errors in data extractions
To: ALFRED WILLIAM THOMSON <alfred.thomson@myfwc.com>, Amy Baker Zimney <BakerA@dnr.sc.gov>, ANALIE BARNETT <abarnett@tnc.org>, AUGUSTIN C ENGMAN <gusengman@gmail.com>, CARLIANE JOHNSON <carliane@seajayenv.com>, CASSIDY PETERSON <cpeterson@vims.edu>, Chris McDonough <McDonoughC@dnr.sc.gov>, CHRISTIAN MICHAEL JONES <christian.jones@noaa.gov>, CHRISTINA SCHOBERND <christina.schobernd@noaa.gov>, DANIEL ZAPF <daniel.zapf@ncdenr.gov>, DANIEL JOSEPH MCGLINN <mcglindj@cofc.edu>, DAVID STEVENSON <david.stevenson@noaa.gov>, DENNIS M. ALLEN <dallen5@sc.rr.com>, DENNIS M. ALLEN <dallen@belle.baruch.sc.edu>, ELI HOLMES <eli.holmes@noaa.gov>, ERIC HAFFEY <diverdude3742@gmail.com>, ERIC HOFFMAYER <eric.hoffmayer@noaa.gov>, ERIN LEVESQUE <erin.levesque@att.net>, Erin Levesque <LevesqueE@dnr.sc.gov>, FRANKLIN ANORUO <Frank@belle.baruch.sc.edu>, GARY MATLOCK <gary.c.matlock@noaa.gov>, GENEVIEVE NESSLAGE <nesslage@umces.edu>, GEOFFREY BELL <gwbell@email.unc.edu>, GEORGE JOYNER <george.joyner@ncdenr.gov>, JAMES MORLEY <jw.morley@rutgers.edu>, JASON MCNAMEE <jason.mcnamee@dem.ri.gov>, JASON ROCK <jason.rock@ncdenr.gov>, JEFF GEARHART <Jeff.Gearhart@noaa.gov>, JEFFREY BRUST <jeffrey.brust@dep.nj.gov>, JENNIFER BOHANNON <jbohannon@quantumspatial.com>, JENNIFER MCHENRY <jennmchenry1@gmail.com>, JOHN CARLSON <john.carlson@noaa.gov>, JOHN QUINLAN <JOHN.A.QUINLAN@noaa.gov>, JOHN F WALTER <john.f.walter@noaa.gov>, JON RICHARDSON <richardsonj@dnr.sc.gov>, Joseph Cowan <CowanJ@dnr.sc.gov>, JOSHUA QUINLAN <joshq2@gmail.com>, JULIA NGUYEN <jnn3285@truman.edu>, JULIA MAE REYNOLDS <jreynolds8@une.edu>, KATIE DREW <kdrew@asmfc.org>, KEVIN BROWN <kevin.h.brown@ncdenr.gov>, LAURA MALEDA LEE <laura.lee@ncdenr.gov>, LINCOLN SMITH <lsmith@researchplanning.com>, MALIN PINSKY <malin.pinsky@rutgers.edu>, MANDY KARNAUSKAS <mandy.karnauskas@noaa.gov>, Marcel Reichert <ReichertM@dnr.sc.gov>, MARK STRATTON <mastratton@vims.edu>, MARK LEWIS BRAGG <marklbragg@gmail.com>, MARY ELIZABETH EGBERT <Beth.Egbert@ncdenr.gov>, MICHAEL ERRIGO <mike.errigo@safmc.net>, NATHAN BAKER <bakernj@g.cofc.edu>, PATRICK HARRIS <harrispa@ecu.edu>, PATRICK J GEER <pat.geer@dnr.state.ga.us>, Pearse Webster <WebsterP@dnr.sc.gov>, RICHARD LAPALME <rlapalme@ec.rr.com>, ROBERT LATOUR <latour@vims.edu>, ROBERT VAN <bvan32@gmail.com>, ROBIN GRUNWALD <robin.grunwald@myfwc.com>, RYAN BATT <battrd@gmail.com>, RYAN DRUYOR <Ryan.Druyor@myfwc.com>, SAMI DOMISCH DOMISCH <domisch@igb-berlin.de>, SARAH ROBERTS <sr197@duke.edu>, SARAH ROBERTS <srobs32@gmail.com>, SCOTT CROSS <sl00p27@gmail.com>, SHANNA MADSEN <smadsen@asmfc.org>, SHELLEY DEARHART <sdearhart@scaquarium.org>, SIMON BROWN <simon.brown@maryland.gov>, SIMON BROWN <simoncbrown@gmail.com>, SPENCER TALMAGE <spencer.talmage@duke.edu>, SPENCER D TALMAGE <stalmage@asmfc.org>, STEPHEN POTTS <spotts2@lsu.edu>, Steve Arnott <ArnottS@dnr.sc.gov>, TIFFANY HOPPER <tiffany.hedrick@ttu.edu>, TINA UDOUJ <tina.udouj@myfwc.com>, TODD KELLISON <todd.kellison@noaa.gov>, TODD MATHES <todd.mathes@ncdenr.gov>, TONY HANCOCK <tlhancock@comcast.net>, TRACEY BAUER <tracey.bauer@ncdenr.gov>, Tracey Smart <SmartT@dnr.sc.gov>, TROY D TUCKEY <tuckey@vims.edu>, TYLER JOHN SWANSON <tswanson5@gmail.com>, VIRGINIA SHERVETTE <virginias@usca.edu>, Wally Bubley <BubleyW@dnr.sc.gov>, WILLIAM B DRIGGERS <william.driggers@noaa.gov>, WILLIAM RICHARD COLLIER <chipcollier1@gmail.com>, zzcmi Wayne McFee <Wayne.mcfee@noaa.gov>

To All SEAMAP-SA database users:

If you have visited the SEAMAP-SA online database website recently, you will have noticed that some data extractions are not currently available.  This is due to an issue with duplicate records produced by the Specimen extraction application for all projects and the Length-Frequency extraction (Pamlico Sound Survey only).  If you have downloaded and are using data from the Specimen extraction from any project or Length-Frequency extraction from the Pamlico Sound Survey applications, please be aware that duplicate records may exist in the data that you have extracted

We are currently working on a resolution of the problem and will follow-up with you soon on this issue.

Please contact the Data Manager via email (BoylanJ@dnr.sc.gov), if you have any questions.

 

Jeanne Boylan
___________________________________________________________________

Jeanne Boylan
Marine Biologist IV
Marine Resources Research Institute
217 Fort Johnson Road
PO Box 12559
Charleston, SC 29422-2559

Office: 843/953-9831
Fax: 843/953-9820
Email:  BoylanJ@dnr.sc.gov
www.SEAMAP.org

**Comment by mstuart1** [comment]
Jeanne Boylan <BoylanJ@dnr.sc.gov>

Michelle,
 
All of the data from the Pamlico Sound Survey were deleted and revised data were imported into the database.  All extractions for the Pamlico Sound Survey are functional.  Please let me know if you have any issues with the database.
 
Jeanne
