### ISSUE TITLE
should we be removing these rows from WCANN?

### ISSUE THREAD

**Issue by mstuart1** [mpinsky/OceanAdapt#80]
@mpinsky while going through the meta data for wcann, I noticed that there is a column called "partition" that contains notes about the catch, including whether the species captured was eggs.  Currently the OA code removes any rows where "egg" is mentioned in the spp column, but it looks like for this survey, egg is mentioned in the partition column instead of the spp column.  Should I update the code to remove rows where egg is in the partition column?

Also, there is a performance column with the values "Satisfactory", "indeterminate", and "unsatisfactory".  Should I remove rows that are unsatisfactory?

**Comment by mpinsky** [comment]
I don't know the answer to either of these questions off the top of my
head. Sound like good questions for the data providers.
