### ISSUE TITLE
Missing projections in new release

### ISSUE THREAD

**Issue by bselden** [mpinsky/OceanAdapt#83]
Gray snapper (Lutjanus griseus) was highlighted as a key species in the Gulf and Southeast in the [Pew Report](https://www.pewtrusts.org/en/research-and-analysis/articles/2018/05/16/warming-waters-to-force-dramatic-shifts-in-marine-species-habitats), but is not in the newest release of OceanAdapt

**Comment by mstuart1** [comment]
When running the old complete.r.script.R on the September 2018 data, which is how the current data on the website was built, Lutjanus griseus was removed when the data was trimmed of species "with not enough data" as the historical comment says, I was told this means that the species was not found in at least 3/4 of the years that the survey was conducted.
